// HYPR Station — Municipal density lookup (IBGE official data)
//
// Loads /assets/mun-density.json (generated by scripts/generate-mun-density.py
// from IBGE Estimativa Populacional 2024 + Malha Municipal 2022) and exposes
// a synchronous lookup by (nome_municipio, uf).
//
// Normalization strategy: accents are stripped and non-alphanumerics become
// underscores, matching the Python generator. UF stays uppercase to prevent
// collisions between homonymous municipios in different states.

interface MunDensityEntry {
  p: number; // população estimada 2024
  a: number; // área km²
  d: number; // densidade hab/km²
}

interface MunDensityPayload {
  version: number;
  source: string;
  generated: string;
  count: number;
  data: Record<string, MunDensityEntry>;
}

let _data: Record<string, MunDensityEntry> | null = null;
let _loading: Promise<Record<string, MunDensityEntry> | null> | null = null;

function normalizeKey(name: string, uf: string): string {
  // NFD decomposes accented chars into base + combining mark; we drop the marks.
  const decomposed = name.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const slug = decomposed
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return `${slug}_${uf.toUpperCase()}`;
}

/**
 * Loads the municipal density dataset. Safe to call multiple times — the
 * fetch is cached. Call this early on the Cell map (e.g. alongside other
 * data loaders) so subsequent synchronous lookups have it ready.
 */
export async function preloadMunDensity(): Promise<Record<string, MunDensityEntry> | null> {
  if (_data) return _data;
  if (_loading) return _loading;

  _loading = fetch('/assets/mun-density.json')
    .then(r => {
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.json() as Promise<MunDensityPayload>;
    })
    .then(payload => {
      _data = payload.data || {};
      return _data;
    })
    .catch(err => {
      console.warn('[MunDensity] failed to load, falling back to UF averages', err);
      _data = {};
      return null;
    });

  return _loading;
}

/**
 * Synchronous lookup. Returns the municipal population density in
 * habitants/km² for the given municipio, or null if unavailable (either
 * because the data hasn't loaded yet or the name didn't match).
 *
 * Callers should have a fallback to UF-level density when this returns null.
 */
export function getMunDensity(
  mun: string | null | undefined,
  uf: string | null | undefined
): number | null {
  if (!_data || !mun || !uf) return null;
  const entry = _data[normalizeKey(mun, uf)];
  return entry ? entry.d : null;
}

/**
 * Full municipal record — useful for popups that want to display population
 * and area alongside the density.
 */
export function getMunStats(
  mun: string | null | undefined,
  uf: string | null | undefined
): MunDensityEntry | null {
  if (!_data || !mun || !uf) return null;
  return _data[normalizeKey(mun, uf)] ?? null;
}
